In [1]:
import torch

In [2]:
a = torch.zeros(3, 4)

In [3]:
torch.sum(a).numpy().item() == 0

True

In [4]:
str(a)

'tensor([[0., 0., 0., 0.],\n        [0., 0., 0., 0.],\n        [0., 0., 0., 0.]])'

In [10]:
board = torch.arange(12).reshape(3, 4)

In [11]:
board

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [20]:
torch.sum(board < 4, dim=-1) 

tensor([4, 0, 0])

In [18]:
(board < 3).int() + (board < 3).int()

tensor([[2, 2, 2, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [21]:
board % 2

tensor([[0, 1, 0, 1],
        [0, 1, 0, 1],
        [0, 1, 0, 1]])

In [4]:
t = torch.Tensor([2])

In [6]:
t.square().sqrt()

tensor([2.])