In [2]:
from tensordict import TensorDict
import torch

In [11]:
ex = TensorDict(
    {
        "f1": torch.arange(12).reshape(2, 3, 2),
        "f2": (torch.arange(6) * 3).reshape(2, 3)
    },
    batch_size=(2,)
)

In [12]:
ex

TensorDict(
    fields={
        f1: Tensor(shape=torch.Size([2, 3, 2]), device=cpu, dtype=torch.int64, is_shared=False),
        f2: Tensor(shape=torch.Size([2, 3]), device=cpu, dtype=torch.int64, is_shared=False)},
    batch_size=torch.Size([2]),
    device=None,
    is_shared=False)

In [41]:
print(ex[0, 0]["f1"])
print(ex[0, 0]["f2"])

tensor([0, 1])
tensor(0)


In [29]:
len(ex)

2

In [42]:
ex.shape

torch.Size([2, 3])

In [44]:
torch.ones(1, 1)

tensor([[1.]])

In [45]:
ex["f1"]

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

In [13]:
test = ex.clone()

In [18]:
test.set("test", torch.Tensor([1, 2]))

TensorDict(
    fields={
        f1: Tensor(shape=torch.Size([2, 3, 2]), device=cpu, dtype=torch.int64, is_shared=False),
        f2: Tensor(shape=torch.Size([2, 3]), device=cpu, dtype=torch.int64, is_shared=False),
        test: Tensor(shape=torch.Size([2]), device=cpu, dtype=torch.float32, is_shared=False)},
    batch_size=torch.Size([2]),
    device=None,
    is_shared=False)

Stacking TensorDict

In [4]:
a = TensorDict(
    {
        "a": torch.Tensor([1, 2, 3])    
    },
    batch_size=()
)

In [9]:
s = torch.stack([a])

In [8]:
a

TensorDict(
    fields={
        a: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False)},
    batch_size=torch.Size([]),
    device=None,
    is_shared=False)

In [10]:
s

LazyStackedTensorDict(
    fields={
        a: Tensor(shape=torch.Size([1, 3]), device=cpu, dtype=torch.float32, is_shared=False)},
    exclusive_fields={
    },
    batch_size=torch.Size([1]),
    device=None,
    is_shared=False,
    stack_dim=0)

In [11]:
s[0, ...]

TensorDict(
    fields={
        a: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False)},
    batch_size=torch.Size([]),
    device=None,
    is_shared=False)