In [2]:
from tensordict import TensorDict
import torch

In [38]:
ex = TensorDict(
    {
        "f1": torch.arange(12).reshape(2, 3, 2),
        "f2": (torch.arange(6) * 3).reshape(2, 3)
    },
    batch_size=(2, 3)
)

In [39]:
ex

TensorDict(
    fields={
        f1: Tensor(shape=torch.Size([2, 3, 2]), device=cpu, dtype=torch.int64, is_shared=False),
        f2: Tensor(shape=torch.Size([2, 3]), device=cpu, dtype=torch.int64, is_shared=False)},
    batch_size=torch.Size([2, 3]),
    device=None,
    is_shared=False)

In [41]:
print(ex[0, 0]["f1"])
print(ex[0, 0]["f2"])

tensor([0, 1])
tensor(0)


In [29]:
len(ex)

2

In [42]:
ex.shape

torch.Size([2, 3])

In [44]:
torch.ones(1, 1)

tensor([[1.]])

In [45]:
ex["f1"]

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])